# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-i, --style=file]
      - id: clang-tidy
        args: [-p=build/dev]
      - id: cppcheck
        args: [--project=build/dev/compile_commands.json, --suppress=unusedFunction, --suppress=unmatchedSuppression, --suppress=noExplicitConstructor, --suppress=useStlAlgorithm, --suppress=missingIncludeSystem, --suppress=normalCheckLevelMaxBranches]
        pass_filenames: false
  - repo: local
    hooks:
      - id: include-what-you-use
        name: include-what-you-use
        entry: bash -c 'iwyu_tool -p build/dev "$@" -- -Xiwyu --cxx17ns' --
        language: system
        files: \.(h|hpp|c|cc|cpp)$
