#pragma once

#include <filesystem>
#include <functional>
#include <optional>
#include <strada/ast/abstract_syntax_tree.hpp>
#include <strada/cpm/compiled_physics_model.hpp>
#include <strada/routing/graph.hpp>
#include <strada/tess/tessellator.hpp>
#include <string_view>

namespace strada {

/// Unified library entry point coordinating AST parsing, physics compiling, routing graph building,
/// and optional tessellation geometry generation.
class Strada {
 public:
  /// Configuration options for the Strada facade.
  struct Options {
    std::optional<double> chord_error;  ///< Chord error tolerance. std::nullopt disables Tessellator.
  };

  /// Constructs a Strada instance by parsing and compiling a map from a file on disk.
  ///
  /// \param file_path The path to the XML/XODR file.
  /// \param options Configuration options.
  /// \throws XmlParseError If the XML is malformed or the file cannot be read.
  /// \throws ParseError If the AST construction fails due to model invariants.
  explicit Strada(const std::filesystem::path& file_path, Options options = {.chord_error = 0.5});

  /// Constructs a Strada instance by parsing and compiling a map from a raw XML string.
  ///
  /// \param xml_content The string view of the XODR/XML map payload.
  /// \param options Configuration options.
  /// \throws XmlParseError If the XML is malformed.
  /// \throws ParseError If the AST construction fails due to model invariants.
  explicit Strada(std::string_view xml_content, Options options = {.chord_error = 0.5});

  // Rule of Zero: Destructor, copy/move constructors, and copy/move assignment operators
  // are implicitly generated by the compiler.

  /// Returns a const reference to the parsed Abstract Syntax Tree.
  [[nodiscard]] auto AbstractSyntaxTree() const noexcept -> const ast::AbstractSyntaxTree&;

  /// Returns a const reference to the Compiled Physics Model.
  [[nodiscard]] auto CompiledPhysicsModel() const noexcept -> const cpm::CompiledPhysicsModel&;

  /// Returns a const reference to the Routing Graph.
  [[nodiscard]] auto Graph() const noexcept -> const routing::Graph&;

  /// Returns an optional reference wrapper to the Tessellator layer.
  ///
  /// Returns std::nullopt if the Tessellator layer was disabled.
  [[nodiscard]] auto Tessellator() const noexcept -> std::optional<std::reference_wrapper<const tess::Tessellator>>;

 private:
  ast::AbstractSyntaxTree ast_;
  cpm::CompiledPhysicsModel cpm_;
  routing::Graph graph_;
  std::optional<tess::Tessellator> tessellator_;
};

}  // namespace strada
